// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lyirvisokusvasnrskcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5aXJ2aXNva3VzdmFzbnJza2NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTU1NTcsImV4cCI6MjA2OTI5MTU1N30.shNZ5yDBM6AARTQvJeqoK64i-Zr2SI6yfniblXDZynA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});